# This playbook will change the required configurations for your AWS server, so we can use the username/password based authentication
---
 - name: This play will do the necessary changes to the aws servers, so they cn be logged in using the credentials.
   hosts: all
   become: True
   serial: "50%"
  
   tasks:
     - name: Disable root login
       lineinfile: 
         dest: /etc/ssh/sshd_config
         regexp: "^PermitRootLogin"
         line: "PermitRootLogin yes"
         state: present
       notify: restart ssh

     - name: Disable password authentication
       lineinfile:
         dest: /etc/ssh/sshd_config
         regexp: "^#?PasswordAuthentication"
         line: "PasswordAuthentication yes"
         state: present
       notify: restart ssh

     - name: restart ssh
       service:
         name: ssh
         state: restarted
