---
 - name: This play is a basic appserverworld execution
   hosts: appservers
   gather_facts: true

   tasks:
     - name: To Install Apache Web Server of the OS is RedHat
       yum: name=httpd state=installed
       when: ansible_os_family == "Ubuntu"

     - name: To Install Apache Web Server of the OS is RedHat
       yum: name=httpd state=installed
       when: ansible_os_family == "RedHat" or ansible_os_family == "CentOS"
